# -*- coding: utf-8 -*-
"""ai_assignment 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sw_EHsNmpF5uVyJwBUPhkYQge95uaZQj
"""

list1 = [12, -7, 5, 64, -14]
print("Positive numbers in list1:")
for num in list1:
    if num > 0:
        print(num, end=" ")

list2 = [12, 14, -95, 3]
positive_nums_list2 = []
for num in list2:
    if num > 0:
        positive_nums_list2.append(num)
print("\nThe positive Numbers in list2 are:", positive_nums_list2)