# -*- coding: utf-8 -*-
"""AI Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hd12aQyOO0lnMH-o6m7uWkeC8Nuq280A
"""

def fibonacci(n):
  fibonacci_sequence = [0,1]
  for _ in range(2,n):
    fibonacci_sequence.append(fibonacci_sequence[-1]+ fibonacci_sequence[-2])
  return fibonacci_sequence

print (fibonacci(20))