# -*- coding: utf-8 -*-
"""AI_assignment06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11czFGpnfKHDzqyQ3KXGFPMzYtoupYJsR
"""

from keras.models import Sequential
from keras.layers import Dense
import pandas as pd

df = pd.read_csv("diabetes.csv")
df.head()

X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

type(X)

X.shape[1]

model = Sequential()

model.add(Dense(12, input_shape=(X.shape[1],),activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X,Y , epochs=100 , batch_size =10)